services:
  app:
    build:
      context: .
      dockerfile: .docker/java/Dockerfile
    ports:
      - "17922:17922"
    environment:
      - SERVER_PORT=17922
    volumes:
      - ./plugins:/app/plugins:ro
