sonar.projectKey=munafsheikh_firefly
sonar.projectName=Firefly
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java,mcp-embedded/src/main/java,plugins/actuator-plugin/src/main/java,plugins/ado-plugin/src/main/java,plugins/bash-runner-plugin/src/main/java,plugins/cli-plugin/src/main/java,plugins/markdown-plugin/src/main/java,plugins/mcp-registry-plugin/src/main/java,plugins/midnight-theme-plugin/src/main/java,plugins/plantuml-plugin/src/main/java,plugins/webtui-plugin/src/main/java

sonar.java.binaries=target/classes,mcp-embedded/target/classes,plugins/actuator-plugin/target/classes,plugins/ado-plugin/target/classes,plugins/bash-runner-plugin/target/classes,plugins/cli-plugin/target/classes,plugins/markdown-plugin/target/classes,plugins/mcp-registry-plugin/target/classes,plugins/midnight-theme-plugin/target/classes,plugins/plantuml-plugin/target/classes,plugins/webtui-plugin/target/classes

sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.exclusions=**/target/**,**/generated/**
